version: '2.0'
services:
  veriumd:
    image: jamesboehmer/verium
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "36988" # peer
      - "32988" # peer testnet
      - "33987" # RPC
      - "32987" # RPC testnet
    command: "launchveriumd"
    environment:
      - RPCPORT
      - RPCUSER
      - RPCPASS
    volumes:
      - "${PWD}/data:/root/.verium"
    restart: always
  cpuminer:
    image: jamesboehmer/verium
    ports:
      - "4048"
    command: "launchcpuminer"
    environment:
      - RPCHOST
      - RPCPORT
      - RPCUSER
      - RPCPASS
    depends_on:
      - veriumd
    restart: always
